version: '3.8'

services:
  frontend:
    build: .
    container_name: mamba-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Útil para que detecte cambios en Windows/Docker
    networks:
      - mamba-network

networks:
  mamba-network:
    driver: bridge